import React from 'react';
import { Monitor, Layout, Zap, Code, Globe } from 'lucide-react';
import { Feature } from './types';

export interface FeatureCategory {
  id: string;
  title: string;
  icon: React.ReactNode;
  features: Feature[];
}

export const FEATURE_CATEGORIES: FeatureCategory[] = [
  {
    id: 'system',
    title: 'System Control',
    icon: <Monitor className="w-5 h-5" />,
    features: [
      { icon: '🧠', title: 'System Info', desc: 'Check PC details easily.' },
      { icon: '🔌', title: 'Power Manager', desc: 'Turn off or restart PC.' },
      { icon: '🔊', title: 'Volume Control', desc: 'Change sound levels.' },
      { icon: '☀️', title: 'Brightness Control', desc: 'Change screen brightness.' },
      { icon: '🛡️', title: 'Virus Scan', desc: 'Check for viruses.' },
      { icon: '🚀', title: 'App Launcher', desc: 'Open any app fast.' },
      { icon: '📂', title: 'File Opener', desc: 'Open any file type.' },
      { icon: '🔋', title: 'Battery Saver', desc: 'Save laptop battery.' },
      { icon: '🌡️', title: 'PC Temp Check', desc: 'Check PC temperature.' },
      { icon: '💾', title: 'Disk Cleaner', desc: 'Clean junk files.' },
      { icon: '🗑️', title: 'Empty Trash', desc: 'Empty recycle bin.' },
      { icon: '📶', title: 'WiFi Manager', desc: 'Connect to WiFi.' },
      { icon: '🌐', title: 'Network Speed', desc: 'Check internet speed.' },
      { icon: '🔒', title: 'Lock Screen', desc: 'Lock your PC.' },
      { icon: '📸', title: 'Screenshot', desc: 'Take a picture of screen.' },
      { icon: '🎥', title: 'Screen Record', desc: 'Record your screen.' },
      { icon: '🎤', title: 'Mic Control', desc: 'Mute or unmute mic.' },
      { icon: '📷', title: 'Webcam Control', desc: 'Turn webcam on/off.' },
      { icon: '🖱️', title: 'Mouse Speed', desc: 'Change mouse speed.' },
      { icon: '⌨️', title: 'Keyboard Lights', desc: 'Change keyboard colors.' },
      { icon: '🕒', title: 'Time Sync', desc: 'Sync PC time.' },
      { icon: '📅', title: 'Calendar View', desc: 'Show calendar.' },
      { icon: '🔔', title: 'Notifications', desc: 'Manage alerts.' },
      { icon: '🌙', title: 'Night Mode', desc: 'Turn on dark mode.' },
      { icon: '👁️', title: 'Eye Care', desc: 'Reduce blue light.' },
      { icon: '🎧', title: 'Bluetooth Connect', desc: 'Connect headphones.' },
      { icon: '🖨️', title: 'Printer Setup', desc: 'Connect to printer.' },
      { icon: '📱', title: 'Phone Link', desc: 'Connect your phone.' },
      { icon: '🎮', title: 'Game Mode', desc: 'Boost game speed.' },
      { icon: '🛠️', title: 'Task Manager', desc: 'Close stuck apps.' },
      { icon: '🔄', title: 'Auto Update', desc: 'Update PC software.' }
    ]
  },
  {
    id: 'desktop',
    title: 'Desktop & Files',
    icon: <Layout className="w-5 h-5" />,
    features: [
      { icon: '🪟', title: 'Window Move', desc: 'Move windows around.' },
      { icon: '↕️', title: 'Auto Scroll', desc: 'Scroll pages for you.' },
      { icon: '🖥️', title: 'Remote Control', desc: 'Control PC from far.' },
      { icon: '📋', title: 'Clipboard History', desc: 'Save copied text.' },
      { icon: '📌', title: 'Pin to Top', desc: 'Keep window on top.' },
      { icon: '🔍', title: 'Quick Search', desc: 'Find files fast.' },
      { icon: '📁', title: 'Folder Maker', desc: 'Make new folders.' },
      { icon: '📝', title: 'Quick Note', desc: 'Take fast notes.' },
      { icon: '🎨', title: 'Change Wallpaper', desc: 'Set new background.' },
      { icon: '🧹', title: 'Clean Desktop', desc: 'Hide all icons.' },
      { icon: '📏', title: 'Screen Ruler', desc: 'Measure things on screen.' },
      { icon: '🎨', title: 'Color Picker', desc: 'Pick colors from screen.' },
      { icon: '✂️', title: 'Snipping Tool', desc: 'Cut parts of screen.' },
      { icon: '🧲', title: 'Snap Windows', desc: 'Snap windows to sides.' },
      { icon: '📺', title: 'Multi Monitor', desc: 'Manage 2+ screens.' },
      { icon: '🔄', title: 'Refresh Desktop', desc: 'Refresh screen.' },
      { icon: '🗑️', title: 'Delete File', desc: 'Delete files fast.' },
      { icon: '📋', title: 'Copy Path', desc: 'Copy file location.' },
      { icon: '🤐', title: 'Zip Files', desc: 'Compress files.' },
      { icon: '📂', title: 'Unzip Files', desc: 'Extract zip files.' },
      { icon: '👀', title: 'Hide Files', desc: 'Hide secret files.' },
      { icon: '👁️', title: 'Show Hidden', desc: 'See hidden files.' },
      { icon: '🏷️', title: 'Rename Files', desc: 'Rename many files.' },
      { icon: '🔗', title: 'Make Shortcut', desc: 'Create shortcuts.' },
      { icon: '🗑️', title: 'Shred File', desc: 'Delete forever.' },
      { icon: '📊', title: 'Folder Size', desc: 'Check folder size.' },
      { icon: '🔄', title: 'Sync Folders', desc: 'Keep folders same.' },
      { icon: '☁️', title: 'Cloud Backup', desc: 'Save to cloud.' },
      { icon: '📥', title: 'Downloads Folder', desc: 'Open downloads.' },
      { icon: '🏠', title: 'Go Home', desc: 'Go to desktop.' },
      { icon: '🚪', title: 'Log Out', desc: 'Log out user.' }
    ]
  },
  {
    id: 'productivity',
    title: 'Productivity & Tools',
    icon: <Zap className="w-5 h-5" />,
    features: [
      { icon: '🌍', title: 'Any Language', desc: 'Speak & understand any language in the world.' },
      { icon: '💬', title: 'WhatsApp Bot', desc: 'Send auto messages.' },
      { icon: '📧', title: 'Email Sender', desc: 'Send emails fast.' },
      { icon: '📝', title: 'Auto Typing', desc: 'Type text for you.' },
      { icon: '⏰', title: 'Set Alarm', desc: 'Set a wake up alarm.' },
      { icon: '⏱️', title: 'Stopwatch', desc: 'Start a stopwatch.' },
      { icon: '⏳', title: 'Timer', desc: 'Set a countdown timer.' },
      { icon: '📅', title: 'Add Event', desc: 'Add to calendar.' },
      { icon: '✅', title: 'To-Do List', desc: 'Manage your tasks.' },
      { icon: '🧮', title: 'Calculator', desc: 'Do math fast.' },
      { icon: '💱', title: 'Currency Converter', desc: 'Convert money.' },
      { icon: '📏', title: 'Unit Converter', desc: 'Convert lengths/weights.' },
      { icon: '🌐', title: 'Translate Text', desc: 'Translate languages.' },
      { icon: '📖', title: 'Dictionary', desc: 'Find word meanings.' },
      { icon: '📚', title: 'Thesaurus', desc: 'Find similar words.' },
      { icon: '🗣️', title: 'Text to Speech', desc: 'Read text out loud.' },
      { icon: '🎤', title: 'Speech to Text', desc: 'Type by talking.' },
      { icon: '📄', title: 'PDF Reader', desc: 'Read PDF files.' },
      { icon: '✍️', title: 'PDF Editor', desc: 'Edit PDF files.' },
      { icon: '📊', title: 'Excel Helper', desc: 'Help with Excel.' },
      { icon: '📝', title: 'Word Helper', desc: 'Help with Word.' },
      { icon: '📽️', title: 'PPT Helper', desc: 'Help with PowerPoint.' },
      { icon: '🧠', title: 'Mind Map', desc: 'Make mind maps.' },
      { icon: '🍅', title: 'Pomodoro Timer', desc: 'Focus timer.' },
      { icon: '🧘', title: 'Relax Mode', desc: 'Play calm sounds.' },
      { icon: '🎵', title: 'Focus Music', desc: 'Play focus music.' },
      { icon: '🚫', title: 'Block Distractions', desc: 'Block bad sites.' },
      { icon: '📈', title: 'Track Time', desc: 'Track work time.' },
      { icon: '🧾', title: 'Make Invoice', desc: 'Create bills.' },
      { icon: '✍️', title: 'Sign Doc', desc: 'Sign documents.' },
      { icon: '📇', title: 'Contacts', desc: 'Manage contacts.' },
      { icon: '🔍', title: 'Find Text', desc: 'Find text in images.' }
    ]
  },
  {
    id: 'dev',
    title: 'Developer & Coding',
    icon: <Code className="w-5 h-5" />,
    features: [
      { icon: '💻', title: 'AI Coder', desc: 'Write code for you.' },
      { icon: '🛠️', title: 'VSCode Link', desc: 'Connect to VSCode.' },
      { icon: '⚡', title: 'Run Code', desc: 'Run code fast.' },
      { icon: '🐛', title: 'Fix Bugs', desc: 'Find and fix bugs.' },
      { icon: '📝', title: 'Format Code', desc: 'Make code look good.' },
      { icon: '🔍', title: 'Explain Code', desc: 'Explain what code does.' },
      { icon: '🔄', title: 'Git Commit', desc: 'Auto git commit.' },
      { icon: '📤', title: 'Git Push', desc: 'Push code to GitHub.' },
      { icon: '📥', title: 'Git Pull', desc: 'Pull code from GitHub.' },
      { icon: '🌿', title: 'Git Branch', desc: 'Make new branch.' },
      { icon: '🐳', title: 'Docker Helper', desc: 'Manage Docker.' },
      { icon: '🗄️', title: 'DB Helper', desc: 'Manage databases.' },
      { icon: '🌐', title: 'API Tester', desc: 'Test APIs.' },
      { icon: '📱', title: 'Mobile View', desc: 'Test mobile view.' },
      { icon: '🎨', title: 'CSS Helper', desc: 'Help with CSS.' },
      { icon: '⚛️', title: 'React Helper', desc: 'Help with React.' },
      { icon: '🐍', title: 'Python Helper', desc: 'Help with Python.' },
      { icon: '☕', title: 'Java Helper', desc: 'Help with Java.' },
      { icon: '📜', title: 'JS Helper', desc: 'Help with JavaScript.' },
      { icon: '🐘', title: 'PHP Helper', desc: 'Help with PHP.' },
      { icon: '💎', title: 'Ruby Helper', desc: 'Help with Ruby.' },
      { icon: '🦀', title: 'Rust Helper', desc: 'Help with Rust.' },
      { icon: '🐹', title: 'Go Helper', desc: 'Help with Go.' },
      { icon: '📝', title: 'Write Tests', desc: 'Write code tests.' },
      { icon: '📊', title: 'Check Speed', desc: 'Check code speed.' },
      { icon: '🔒', title: 'Check Security', desc: 'Check code security.' },
      { icon: '📚', title: 'Read Docs', desc: 'Read code docs.' },
      { icon: '✍️', title: 'Write Docs', desc: 'Write code docs.' },
      { icon: '🚀', title: 'Deploy App', desc: 'Deploy your app.' },
      { icon: '☁️', title: 'AWS Helper', desc: 'Help with AWS.' },
      { icon: '🐧', title: 'Linux Commands', desc: 'Run Linux commands.' }
    ]
  },
  {
    id: 'web',
    title: 'Web & Media',
    icon: <Globe className="w-5 h-5" />,
    features: [
      { icon: '🔍', title: 'Web Search', desc: 'Search the web.' },
      { icon: '🌦️', title: 'Weather Info', desc: 'Check the weather.' },
      { icon: '📰', title: 'Daily News', desc: 'Read top news.' },
      { icon: '🎵', title: 'Play Music', desc: 'Play any song.' },
      { icon: '▶️', title: 'Play Video', desc: 'Play YouTube videos.' },
      { icon: '📸', title: 'Find Images', desc: 'Search for pictures.' },
      { icon: '🎬', title: 'Movie Info', desc: 'Find movie details.' },
      { icon: '📚', title: 'Book Info', desc: 'Find book details.' },
      { icon: '✈️', title: 'Flight Info', desc: 'Check flight status.' },
      { icon: '🏨', title: 'Hotel Search', desc: 'Find hotels.' },
      { icon: '🗺️', title: 'Maps & Routes', desc: 'Find directions.' },
      { icon: '🍔', title: 'Food Delivery', desc: 'Order food.' },
      { icon: '🛒', title: 'Shop Online', desc: 'Search products.' },
      { icon: '📦', title: 'Track Package', desc: 'Track your order.' },
      { icon: '📈', title: 'Stock Prices', desc: 'Check stock market.' },
      { icon: '🪙', title: 'Crypto Prices', desc: 'Check crypto market.' },
      { icon: '⚽', title: 'Sports Scores', desc: 'Check live scores.' },
      { icon: '🎮', title: 'Game Info', desc: 'Find game details.' },
      { icon: '🤣', title: 'Tell a Joke', desc: 'Hear a funny joke.' },
      { icon: '📖', title: 'Daily Quote', desc: 'Read a good quote.' },
      { icon: '🧘', title: 'Meditation', desc: 'Guided meditation.' },
      { icon: '🏋️', title: 'Workout Plan', desc: 'Get a workout plan.' },
      { icon: '🥗', title: 'Diet Plan', desc: 'Get a diet plan.' },
      { icon: '🍳', title: 'Recipes', desc: 'Find cooking recipes.' },
      { icon: '🍷', title: 'Wine Pairing', desc: 'Find good wine.' },
      { icon: '🐾', title: 'Pet Care', desc: 'Pet care tips.' },
      { icon: '🌱', title: 'Plant Care', desc: 'Plant care tips.' },
      { icon: '🚗', title: 'Car Info', desc: 'Find car details.' },
      { icon: '🏠', title: 'Home Decor', desc: 'Home decor ideas.' },
      { icon: '👗', title: 'Fashion Tips', desc: 'Get fashion advice.' },
      { icon: '💄', title: 'Makeup Tips', desc: 'Get makeup advice.' }
    ]
  }
];

export const ELITE_FEATURES: Feature[] = FEATURE_CATEGORIES.flatMap(c => c.features);
